# browser types:  chrome. firefox, edge, safari
browser=chrome
#Execution types: local, LocalHeadless, Remote
executionType=LocalHeadless
#IgnoreExtensions types: enable, disable
ignoreExtensions=enable

